markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: panxw
author: "Ruben"
email: lingyunzi09#gmail.com
name: "My Blog"
url: http://blog.rubenxiao.com
domain: blog.rubenxiao.com
all_categories: [
["Pytorch", "Pytorch","/posts/pytorch.html"], 
["Gensim", "Gensim","/posts/gensim.html"],
["Neo4J", "Neo4J","/posts/neo4j.html"], 
["Deep Learning", "深度学习","/posts/dl.html"],
["Machine Learning", "机器学习","/posts/ml.html"], 
["other", "杂记","/posts/other.html"],
["translation", "翻译","/posts/tanslation.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: China/Shanghai

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
